/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as SaidasRouteImport } from './routes/saidas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as ImportarExportarRouteImport } from './routes/importar-exportar'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FiadoRouteImport } from './routes/fiado'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComercioRouteImport } from './routes/comercio'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as FinanceiroSetoresRouteImport } from './routes/financeiro.setores'
import { Route as FinanceiroPerdasRouteImport } from './routes/financeiro.perdas'
import { Route as FinanceiroDreRouteImport } from './routes/financeiro.dre'
import { Route as FinanceiroDividasRouteImport } from './routes/financeiro.dividas'
import { Route as FinanceiroDespesasRouteImport } from './routes/financeiro.despesas'
import { Route as FinanceiroCurvaAbcRouteImport } from './routes/financeiro.curva-abc'
import { Route as FinanceiroContasReceberRouteImport } from './routes/financeiro.contas-receber'
import { Route as FinanceiroContasPagarRouteImport } from './routes/financeiro.contas-pagar'
import { Route as FinanceiroBalancoRouteImport } from './routes/financeiro.balanco'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const SaidasRoute = SaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarExportarRoute = ImportarExportarRouteImport.update({
  id: '/importar-exportar',
  path: '/importar-exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FiadoRoute = FiadoRouteImport.update({
  id: '/fiado',
  path: '/fiado',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercioRoute = ComercioRouteImport.update({
  id: '/comercio',
  path: '/comercio',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroSetoresRoute = FinanceiroSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroPerdasRoute = FinanceiroPerdasRouteImport.update({
  id: '/perdas',
  path: '/perdas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroDreRoute = FinanceiroDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroDividasRoute = FinanceiroDividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroDespesasRoute = FinanceiroDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroCurvaAbcRoute = FinanceiroCurvaAbcRouteImport.update({
  id: '/curva-abc',
  path: '/curva-abc',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroContasReceberRoute = FinanceiroContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroContasPagarRoute = FinanceiroContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroBalancoRoute = FinanceiroBalancoRouteImport.update({
  id: '/balanco',
  path: '/balanco',
  getParentRoute: () => FinanceiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/comercio': typeof ComercioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entradas': typeof EntradasRoute
  '/fiado': typeof FiadoRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fornecedores': typeof FornecedoresRoute
  '/importar-exportar': typeof ImportarExportarRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/saidas': typeof SaidasRoute
  '/vendas': typeof VendasRoute
  '/financeiro/balanco': typeof FinanceiroBalancoRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/curva-abc': typeof FinanceiroCurvaAbcRoute
  '/financeiro/despesas': typeof FinanceiroDespesasRoute
  '/financeiro/dividas': typeof FinanceiroDividasRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/perdas': typeof FinanceiroPerdasRoute
  '/financeiro/setores': typeof FinanceiroSetoresRoute
  '/financeiro/': typeof FinanceiroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/comercio': typeof ComercioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entradas': typeof EntradasRoute
  '/fiado': typeof FiadoRoute
  '/fornecedores': typeof FornecedoresRoute
  '/importar-exportar': typeof ImportarExportarRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/saidas': typeof SaidasRoute
  '/vendas': typeof VendasRoute
  '/financeiro/balanco': typeof FinanceiroBalancoRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/curva-abc': typeof FinanceiroCurvaAbcRoute
  '/financeiro/despesas': typeof FinanceiroDespesasRoute
  '/financeiro/dividas': typeof FinanceiroDividasRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/perdas': typeof FinanceiroPerdasRoute
  '/financeiro/setores': typeof FinanceiroSetoresRoute
  '/financeiro': typeof FinanceiroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/comercio': typeof ComercioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entradas': typeof EntradasRoute
  '/fiado': typeof FiadoRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fornecedores': typeof FornecedoresRoute
  '/importar-exportar': typeof ImportarExportarRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/saidas': typeof SaidasRoute
  '/vendas': typeof VendasRoute
  '/financeiro/balanco': typeof FinanceiroBalancoRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/curva-abc': typeof FinanceiroCurvaAbcRoute
  '/financeiro/despesas': typeof FinanceiroDespesasRoute
  '/financeiro/dividas': typeof FinanceiroDividasRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/perdas': typeof FinanceiroPerdasRoute
  '/financeiro/setores': typeof FinanceiroSetoresRoute
  '/financeiro/': typeof FinanceiroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assinatura'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/comercio'
    | '/configuracoes'
    | '/entradas'
    | '/fiado'
    | '/financeiro'
    | '/fornecedores'
    | '/importar-exportar'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/saidas'
    | '/vendas'
    | '/financeiro/balanco'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/curva-abc'
    | '/financeiro/despesas'
    | '/financeiro/dividas'
    | '/financeiro/dre'
    | '/financeiro/perdas'
    | '/financeiro/setores'
    | '/financeiro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assinatura'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/comercio'
    | '/configuracoes'
    | '/entradas'
    | '/fiado'
    | '/fornecedores'
    | '/importar-exportar'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/saidas'
    | '/vendas'
    | '/financeiro/balanco'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/curva-abc'
    | '/financeiro/despesas'
    | '/financeiro/dividas'
    | '/financeiro/dre'
    | '/financeiro/perdas'
    | '/financeiro/setores'
    | '/financeiro'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assinatura'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/comercio'
    | '/configuracoes'
    | '/entradas'
    | '/fiado'
    | '/financeiro'
    | '/fornecedores'
    | '/importar-exportar'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/saidas'
    | '/vendas'
    | '/financeiro/balanco'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/curva-abc'
    | '/financeiro/despesas'
    | '/financeiro/dividas'
    | '/financeiro/dre'
    | '/financeiro/perdas'
    | '/financeiro/setores'
    | '/financeiro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AuthRoute: typeof AuthRoute
  CaixaRoute: typeof CaixaRoute
  ClientesRoute: typeof ClientesRoute
  ComercioRoute: typeof ComercioRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EntradasRoute: typeof EntradasRoute
  FiadoRoute: typeof FiadoRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  FornecedoresRoute: typeof FornecedoresRoute
  ImportarExportarRoute: typeof ImportarExportarRoute
  PdvRoute: typeof PdvRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SaidasRoute: typeof SaidasRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saidas': {
      id: '/saidas'
      path: '/saidas'
      fullPath: '/saidas'
      preLoaderRoute: typeof SaidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-exportar': {
      id: '/importar-exportar'
      path: '/importar-exportar'
      fullPath: '/importar-exportar'
      preLoaderRoute: typeof ImportarExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiado': {
      id: '/fiado'
      path: '/fiado'
      fullPath: '/fiado'
      preLoaderRoute: typeof FiadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercio': {
      id: '/comercio'
      path: '/comercio'
      fullPath: '/comercio'
      preLoaderRoute: typeof ComercioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/setores': {
      id: '/financeiro/setores'
      path: '/setores'
      fullPath: '/financeiro/setores'
      preLoaderRoute: typeof FinanceiroSetoresRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/perdas': {
      id: '/financeiro/perdas'
      path: '/perdas'
      fullPath: '/financeiro/perdas'
      preLoaderRoute: typeof FinanceiroPerdasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/dre': {
      id: '/financeiro/dre'
      path: '/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof FinanceiroDreRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/dividas': {
      id: '/financeiro/dividas'
      path: '/dividas'
      fullPath: '/financeiro/dividas'
      preLoaderRoute: typeof FinanceiroDividasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/despesas': {
      id: '/financeiro/despesas'
      path: '/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof FinanceiroDespesasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/curva-abc': {
      id: '/financeiro/curva-abc'
      path: '/curva-abc'
      fullPath: '/financeiro/curva-abc'
      preLoaderRoute: typeof FinanceiroCurvaAbcRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/contas-receber': {
      id: '/financeiro/contas-receber'
      path: '/contas-receber'
      fullPath: '/financeiro/contas-receber'
      preLoaderRoute: typeof FinanceiroContasReceberRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/contas-pagar': {
      id: '/financeiro/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof FinanceiroContasPagarRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/balanco': {
      id: '/financeiro/balanco'
      path: '/balanco'
      fullPath: '/financeiro/balanco'
      preLoaderRoute: typeof FinanceiroBalancoRouteImport
      parentRoute: typeof FinanceiroRoute
    }
  }
}

interface FinanceiroRouteChildren {
  FinanceiroBalancoRoute: typeof FinanceiroBalancoRoute
  FinanceiroContasPagarRoute: typeof FinanceiroContasPagarRoute
  FinanceiroContasReceberRoute: typeof FinanceiroContasReceberRoute
  FinanceiroCurvaAbcRoute: typeof FinanceiroCurvaAbcRoute
  FinanceiroDespesasRoute: typeof FinanceiroDespesasRoute
  FinanceiroDividasRoute: typeof FinanceiroDividasRoute
  FinanceiroDreRoute: typeof FinanceiroDreRoute
  FinanceiroPerdasRoute: typeof FinanceiroPerdasRoute
  FinanceiroSetoresRoute: typeof FinanceiroSetoresRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroBalancoRoute: FinanceiroBalancoRoute,
  FinanceiroContasPagarRoute: FinanceiroContasPagarRoute,
  FinanceiroContasReceberRoute: FinanceiroContasReceberRoute,
  FinanceiroCurvaAbcRoute: FinanceiroCurvaAbcRoute,
  FinanceiroDespesasRoute: FinanceiroDespesasRoute,
  FinanceiroDividasRoute: FinanceiroDividasRoute,
  FinanceiroDreRoute: FinanceiroDreRoute,
  FinanceiroPerdasRoute: FinanceiroPerdasRoute,
  FinanceiroSetoresRoute: FinanceiroSetoresRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssinaturaRoute: AssinaturaRoute,
  AuthRoute: AuthRoute,
  CaixaRoute: CaixaRoute,
  ClientesRoute: ClientesRoute,
  ComercioRoute: ComercioRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EntradasRoute: EntradasRoute,
  FiadoRoute: FiadoRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  FornecedoresRoute: FornecedoresRoute,
  ImportarExportarRoute: ImportarExportarRoute,
  PdvRoute: PdvRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SaidasRoute: SaidasRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
