/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaidasRouteImport } from './routes/saidas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'

const SaidasRoute = SaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/entradas': typeof EntradasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/produtos': typeof ProdutosRoute
  '/saidas': typeof SaidasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/entradas': typeof EntradasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/produtos': typeof ProdutosRoute
  '/saidas': typeof SaidasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/entradas': typeof EntradasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/produtos': typeof ProdutosRoute
  '/saidas': typeof SaidasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/entradas'
    | '/fornecedores'
    | '/produtos'
    | '/saidas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/entradas'
    | '/fornecedores'
    | '/produtos'
    | '/saidas'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/entradas'
    | '/fornecedores'
    | '/produtos'
    | '/saidas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  EntradasRoute: typeof EntradasRoute
  FornecedoresRoute: typeof FornecedoresRoute
  ProdutosRoute: typeof ProdutosRoute
  SaidasRoute: typeof SaidasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saidas': {
      id: '/saidas'
      path: '/saidas'
      fullPath: '/saidas'
      preLoaderRoute: typeof SaidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  EntradasRoute: EntradasRoute,
  FornecedoresRoute: FornecedoresRoute,
  ProdutosRoute: ProdutosRoute,
  SaidasRoute: SaidasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
